controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\ValidarFormulario;
use app\models\ValidarFormularioAjax;
use yii\widgets\ActiveForm;
use app\models\Usuarios;
use app\models\FormUsuarios;
use app\models\FormDeleteUsuarios;
use app\models\FormSearch;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\data\Pagination;






class SiteController extends Controller//herdada de siteController
{
    /**
     * @inheritdoc
     */
    
    public function actionPruebados(){
        
        return $this->render('p2');
    }
    
    public function actionUpdate(){
        
        $model = new FormUsuarios();
        $msg = null;
        
        if($model->load(Yii::$app->request->post())){
            
            if($model ->validate()){
                
                $table = Usuarios::findOne($model->id);
                
                if($table){
                    
                    $table->nombre = $model->nombre;
                    $table->apellido = $model->apellido;
                    $table->empresa = $model->empresa;
                    $table->capital = $model->capital;
                    $table->contrasena = $model->contrasena;
                    
                    if($table->update()){
                        $msg = "El alumno ha sido actualizado correctamente";
                        
                    }else{
                        
                          $msg = "El alumno no ha podido ser actualizado";
                        }
                }else{
                    $msg = "El alumno seleccionado no ha sido encontrado";
                }
            }
   
        }else{
            $model->getErrors();
        }
        
        return $this->render('modificar');
    }
    
    public function actionDelete(){
        
        if(Yii::$app->request->post()){
            
            $id = Html::encode($_POST["id"]);
            
            if((int) $id){
                
                if(Usuarios::deleteAll("id=:id" , [":id" => $id])){
                    
                    echo " El usuario con id $id ha sido eliminado con exito,resireccionando...";
                    echo " <meta http-equiv='refresh content='3; ".Url::toRoute("site/viewusuario")."'>";
                    
                }else{
                    
                    echo " Ha ocurrido un ERROR ,el usuario con id $id NO ha sido eliminado ,resireccionando...";
                    echo " <meta http-equiv='refresh content='3; ".Url::toRoute("site/viewusuario")."'>";
                }
                
            }else{
                
                echo " Ha ocurrido un ERROR ,el usuario con id $id NO ha sido eliminado ,resireccionando...";
                echo " <meta http-equiv='refresh content='3; ".Url::toRoute("site/viewusuario")."'>";
            }
           
                
        }else{
            
           return $this->redirect(["site/viewusuario"]);
            
        }
    }
    
    public function actionViewusuario(){
       /*Sirve para listar una tabla y buscra un usuario por id nombre y apellido*/
      /*  $table = new Usuarios();
        $model = $table ->find()->all();
        
        $form = new FormSearch();
        $search = null;
        
        if($form->load(Yii::$app->request->get())){
            
            if($form->validate()){
                $search = Html::encode($form->q);
                $query = "SELECT * FROM usuarios WHERE id LIKE '%$search%' OR ";
                $query .= "nombre LIKE '%$search%' OR apellido LIKE '%$search%'";
                $model = $table->findBySql($query)->all();
            }else{
                
                $form->getErrors();
            }
        }*/
        
        $form = new FormSearch();
        $search = null;
        
        if($form->load(Yii::$app->request->get())){
            
            if($form->validate()){
               
                $search = Html::encode($form->q);
                $table = Usuarios::find()
                ->where(["like","id",$search])
                ->orwhere(["like","nombre",$search])
                ->orwhere(["like","apellido",$search]);
                
                $count = clone $table;
                $pages = new Pagination([
                    "pageSize"=> 25,
                    "totalCount" => $count->count()
                    
                ]);
                
                $model = $table 
                ->offset($pages->offset)
                ->limit($pages->limit)
                ->all();
            }else{
                
                $form->getErrors();
            }
        }else{
            
            $table = Usuarios::find();
            $count = clone $table;
            $pages = new Pagination([
                "pageSize" => 25,
                "totalCount" => $count->count()
            ]);
            
            $model = $table
            -> offset($pages->offset)
            ->limit($pages->limit)
            ->all();
            
        }
        
        
        return $this->render('viewusuario',
                ['model' => $model,
                 'form'=>$form ,
                 'search'=>$search, 
                 'pages'=> $pages]);
        
    }
    /**
     * Metodo para la conexion de la base de datos;
     */
    public function actionUsuarios(){
        $model = new FormUsuarios();
        
        $msg = null;
        
        if ($model->load(Yii::$app->request->post())) {
            
            if ($model->validate()) {
                
                $table = new Usuarios();
                
                $table->nombre = $model->nombre;
                $table->apellido = $model->apellido;
                $table->empresa = $model->empresa;
                $table->capital = $model->capital;
                $table->contrasena = $model->contrasena;
                
                if ($table->insert()) {
                    $msg = 'Muy bien david has logrado introducir tus primeros datos mediante PHP';
                    
                    $model->nombre = null;
                    $model->apellido = null;
                    $model->empresa = null;
                    $model->capital = null;
                    $model->contrasena = null;
                } else {
                    $msg = "Ha ocurrido un error,mira que eres torpe";
                }
            } else {
                
                $model->getErrors();
            }
            
        }
        return $this->render('usuarios', [
            'model' => $model,
            'msg' => $msg
        ]);
    }
    
    public function actionDeleteusuario(){
        
        $model = new FormDeleteUsuarios();
        $msg = null;
        
        if ($model->load(Yii::$app->request->post())) {
            if ($model->delete()) {
                
                $msg = 'Usuario eliminado';
                
                $model->nombre = null;
                $model->apellido = null;
                $model->empresa = null;
                $model->capital = null;
                $model->contrasena = null;
            } else {
                $msg = "Ha ocurrido un error, XD";
            }
        }
        
        return $this->render('deleteusuario', [
            'model' => $model,
            'msg' => $msg
        ]);
        
        
    }
        
    
    /**
     * esto es como un metodo en java que pasa un parametro en este caso de texto
     * y numeros y ademas una variable propia del metodo ($get) que hemos inicializado
     * cada variable se puede usar en ela view/site saludar.php
     */
    public function actionSaludar($get = "Tutoria Yii"){
        
        $mensaje = "Fuck the worlD!!!!";
        $numeros = [0,1,2,3,4,5,6,7,8,9];
        return $this->render("saludar", [
            "mensaje" => $mensaje,
            "arraynum" => $numeros,
            "get" => $get
            
        ]);
    }
    
    public function actionFormulario($mensaje = null){
        
        return $this->render('formulario' , ["mensaje" => $mensaje]);
    }
    
    public function actionRequest(){
        $mensaje = null;
        if(isset($_REQUEST["nombre"])){
            //este mensaje se lo vamos a pasr a la vista formulario
            $mensaje  = 'Enviado correctamente tu nombre: ' .$_REQUEST["nombre"];
        }
        return $this->redirect(['site/formulario',"mensaje"=> $mensaje]);
    }
    
    
   public function actionValidarformulario(){
       
       $model = new ValidarFormulario();
       
       if($model ->load(Yii::$app->request->post())){
           
           if($model->validate()){
               
               //TODO comprpbar con una DB
           }else{
               $model->getErrors();
           }
       }
       
       return $this->render('validarformulario' , ["model" => $model]);
              
   }
   
   public function actionValidarformularioajax(){
       $model = new ValidarFormularioAjax();
       $msg = null;
       
       if($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax){
           
           Yii::$app->response->format = Response::FORMAT_JSON;
           Return ActiveForm::validate($model);
       }
       
       if($model ->load(Yii::$app->request->post())){
           
           if($model->validate()){
               
               //TODO comprpbar con una DB
               $msg = 'Enhorabuena formulario enviado';
               $model->nombre=null;
               $model->email=null;
           }else{
               $model->getErrors();
           }
       }
       
       return $this->render('validarformularioajax' , ["model" => $model,'msg' => $msg]);
   }
    
    public function behaviors()
    {
        return [
            'access' => [

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/deleteusuario.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<h1> Formulario Eliminar Usuario</h1>
<h3><?= $msg ?></h3>
<?php 
    $form = ActiveForm::begin([
        'method' => "post",
        'enableClientValidation' => true,
        
    ]);
?>


<div class ="form-group">
	<?= $form->field($model, "nombre")->input("text") ?>
</div>

<div class = "form-group">
	<?= $form->field($model, "apellido")->input("text")?>
</div>

<div class = "form-group">
	<?= $form->field($model, "empresa")->input("text")?>
</div>

<div class = "form-group">
	<?= $form->field($model, "capital")->input("text")?>
</div>

<div class = "form-group">
	<?= $form->field($model, "contrasena")->input("text")?>
</div>

<?= Html::submitButton("Eliminar" ,["class"=> "btn btn-primary"])?>

<?php  $form->end() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/formulario.php
<?php
use yii\helpers\Url;//Trabajar con Urls
use yii\helpers\Html;//Trabajar con html
?>

<h1>Formulario</h1>
<h3><?= $mensaje ?></h3>
<?= Html::beginForm(
            Url::toRoute("site/request"),//action
            "get",//method
            ['class'=>'form-inline']//options
            );
?>

        <div class="form-group">
            <?= Html::label("Introduce tu nombre", "nombre")?>
            <?= Html::textInput("nombre", null , ["class" => "btn btn-primary"])?>
        
        </div>
    
<?= Html::submitInput("Enviar nombre",["class" => "btn btn-primary"])?>    

<?= /*Fin de nuestro formulario */Html::endForm() ?>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Enhorabuena lo has logrado XD!</h1>

        <p class="lead">Ahora vas a conocer el pode de Yii2 que es un coñazo  instalarlo
		pero algo bueno dbe tener.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Enlace a la pagina de yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Primer parrafo</h2>

                <p>BLA BLA BLA Y BLA</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Documentacion de yii</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Segundo Parrafo</h2>

                <p>Pues parce que nos enteramos</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Foro de yii</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Tercer parrafo</h2>

                <p>Menuda cagada que hicimos el viernes uff menos mal que ya esta 
				solucionado
				jejejejejeje , hacerlo todo d nuevo en solo 2 horas , mmmm</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Extensiones de yii</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Rellena los campos nombre de usuario y contraseña:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/modificar.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
?>

<a href="<?= Url::toRoute("site/viewusuario") ?>">Ir a la lista de usuarios</a>

<h1>Editar alumno con id <?= Html::encode($_GET["id"]) ?></h1>

<h3><?= $msg ?></h3>

<?php $form = ActiveForm::begin([
    "method" => "post",
    'enableClientValidation' => true,
]);
?>

<?= $form->field($model, "id")->input("hidden")->label(false) ?>

<div class="form-group">
 <?= $form->field($model, "nombre")->input("text") ?>   
</div>

<div class="form-group">
 <?= $form->field($model, "apellidos")->input("text") ?>   
</div>

<div class="form-group">
 <?= $form->field($model, "empresa")->input("text") ?>   
</div>

<div class="form-group">
 <?= $form->field($model, "capital")->input("text") ?>   
</div>

<div class="form-group">
 <?= $form->field($model, "contrasena")->input("text") ?>   
</div>

<?= Html::submitButton("Actualizar", ["class" => "btn btn-primary"]) ?>

<?php $form->end() ?>

views/site/prueba.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<h1>Preuba de Formulario</h1>
<?php $form = ActiveForm::begin([
    "method" => "post",'enableClientValidation' => true,
]);
?>
<div class="form-group">
 <?= $form->field($model, "nombre")->input("text") ?>   
</div>

<div class="form-group">
 <?= $form->field($model, "email")->input("email") ?>   
</div>

<?= Html::submitButton("Enviar", ["class" => "btn btn-primary"]) ?>

<?php $form->end() ?>

views/site/saludar.php
<?= $mensaje
    
?>


<?php 
# en el foreach metemos los valores fel array que viene del controller
# en una variable llamada valor
    foreach($arraynum as $valor): ?>
        <p><strong><?= $valor ?></strong></p>
    
<?php endforeach;

?>

<h1><?= $get ?></h1>

views/site/usuarios.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
?>

<a href="<?= Url::toRoute("site/viewusuario") ?>">Ir a la lista de alumnos</a>
<h1> Formulario crear Usuario</h1>
<h3><?= $msg ?></h3>
<?php 
    $form = ActiveForm::begin([
        'method' => "post",
        'enableClientValidation' => true,
        
    ]);
?>


<div class ="form-group">
	<?= $form->field($model, "nombre")->input("text") ?>
</div>

<div class = "form-group">
	<?= $form->field($model, "apellido")->input("text")?>
</div>

<div class = "form-group">
	<?= $form->field($model, "empresa")->input("text")?>
</div>

<div class = "form-group">
	<?= $form->field($model, "capital")->input("text")?>
</div>

<div class = "form-group">
	<?= $form->field($model, "contrasena")->input("text")?>
</div>

<?= Html::submitButton("Enviar" ,["class"=> "btn btn-primary"])?>

<?= Html::submitButton("Eliminar" ,["class"=> "btn btn-primary"])?>

<?php  $form->end() ?>

views/site/validarformulario.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<h1> Validar Formularios</h1>
<?php 
    $form = ActiveForm::begin([
        "method" => "post",
        'enableClientValidation' => true,
    ]);
?>

<div class ="form-group">
	<?= $form->field($model, "nombre")->input("text") ?>
</div>

<div class = "form-group">
	<?= $form->field($model, "email")->input("text")?>
</div>

<?= Html::submitButton("Enviar" ,["class"=> "btn btn-primary"])?>

<?php  $form->end() ?>

views/site/validarformularioajax.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<h1> Validar Formularios AJAX</h1>
<?php 
    $form = ActiveForm::begin([
        'method' => "post",
        'id' => "formulario",
        'enableClientValidation' => true,
        'enableAjaxValidation' => true,
    ]);
?>

<div class ="form-group">
	<?= $form->field($model, "nombre")->input("text") ?>
</div>

<div class = "form-group">
	<?= $form->field($model, "email")->input("text")?>
</div>

<?= Html::submitButton("Enviar" ,["class"=> "btn btn-primary"])?>

<?php  $form->end() ?>